id: P57A14425
initial_creation_type: input
source_metadata:
  title: Orgyen Tendzin Norbu Series
  language: en
  description: 'Texts by and about Orgyen Tendzin Norbu (o rgyan bstan ''dzin nor
    bu, 1841–1900), one of the main disciples of Dza Patrul Rinpoche:'
  volume:
    b1f097f72cf3488e91f3ebd01a3faeb8:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
created_at: '2022-03-01T01:07:35.101211'
last_modified_at: '2022-03-01T01:07:35.101217'
